server:
  port: 8080
  servlet:
    context-path: /employee-registration
spring:
  datasource:
    name: db_employee-registration
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      pool-name: AccountConnectionPool
#      maximum-pool-size: 20
#      minimum-idle: 3
  flyway:
    enabled: true
    locations: classpath:/db/migration/
    baseline-on-migrate: true
    encoding: UTF-8